version: '3.9'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
  backend:
    build: .
    container_name: hbp_backend_python
    environment:
      - ELASTIC_SEARCH_URL=http://localhost:9200
    ports:
      - 5000:5000
    depends_on:
      - es01
    links:
      - es01


volumes:
  data01:
    driver: local
