version: '3.9'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
  backend:
    build: .
    environment:
      - ELASTIC_SEARCH_URL=http://es01:9200
      - HBP_AUTH_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6ImJicC1vaWRjIn0.eyJleHAiOjE2MTAwNTI0OTcsInN1YiI6IjMxMDEwNyIsImF1ZCI6WyIzMjMxNDU3My1hMjQ1LTRiNWEtYjM3MS0yZjE1YWNjNzkxYmEiXSwiaXNzIjoiaHR0cHM6XC9cL3NlcnZpY2VzLmh1bWFuYnJhaW5wcm9qZWN0LmV1XC9vaWRjXC8iLCJqdGkiOiI5ODZlZTEwMi1hZWI4LTQ0MzAtYTVkOC05NGRiNmI3MTkxNjMiLCJpYXQiOjE2MTAwMzgwOTcsImhicF9rZXkiOiIxOTJiOWVhY2I2ZGE0YmMwNmZlMDZmZDc2OTI3OTlkNGQ5MWJhN2Y4In0.bPhydQ0sTyzv83X72_iaqARltm6H7SWkbxyhqKaz5BIGZgGj-wDb785cz4Clsb5FMnlECHwKHxSsLsk4rQ7o6VOwQiheC56VYttNMIl43Wkksb-afYI2fQB148sLlCAiwAmb2099SDcVuwMcPTEP9Crtrka7zwqZl5AiyzZHdQ8
    ports:
      - 5000:5000
    depends_on:
      - es01
    links:
      - es01


volumes:
  data01:
    driver: local
