version: '3.9'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    volumes:
      - data01:/usr/share/elasticsearch/data
    expose:
      - 9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kib01
    depends_on:
      - es01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
  backend:
    build: .
    container_name: hbp_backend_python
    restart: on-failure
    environment:
      - ELASTIC_SEARCH_URL=http://es01:9200
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://es01:9200/_cat/health?h=st) = 200 ]
      - WAIT_START_CMD=python app.py
      - WAIT_SLEEP=2
      - WAIT_LOOPS=10
    ports:
      - 80:5000
    depends_on:
      - es01
    links:
      - es01


volumes:
  data01:
    driver: local